name: Preprocessing Dataset

on:
  push:
    branches:
      - main
    paths:
      - 'dataset/*'  # Trigger jika ada perubahan di folder dataset

jobs:
  preprocessing:
    runs-on: ubuntu-latest  # Menjalankan di environment Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Mengambil kode dari repositori

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  # Menggunakan Python versi 3.12.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn  # Menginstal dependensi untuk preprocessing

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Putri_Nanda-Sari.py  # Menjalankan script preprocessing

    - name: Commit processed dataset to repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
        if [ -f preprocessing/processed_dataset.csv ]; then
          git add preprocessing/processed_dataset.csv
          git add preprocessing/processed_dataset_encoders.json || true
          git commit -m "Automated preprocessing"
          git push origin HEAD:${{ github.ref }}
        else
          echo "❌ File processed_dataset.csv not found. Skipping commit."
          exit 1
        fi

