name: Preprocessing Dataset

on:
  push:
    branches:
      - main
    paths:
      - 'dataset/*'  # Trigger jika ada perubahan di folder dataset

jobs:
  preprocessing:
    runs-on: ubuntu-latest  # Menjalankan di environment Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Mengambil kode dari repositori

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  # Menggunakan Python versi 3.12.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn  # Menginstal dependensi untuk preprocessing

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Nama-siswa.py  # Menjalankan script preprocessing

    - name: Commit processed dataset
      run: |
        git config --global user.name 'GitHub Actions'  # Menyiapkan identitas pengguna
        git config --global user.email 'actions@github.com'  # Menyiapkan email pengguna
        git add preprocessing/processed_dataset.csv  # Menambahkan file yang sudah diproses ke folder preprocessing
        git commit -m "Automated preprocessing"  # Commit hasil preprocessing
        
        # Gunakan Personal Access Token (PAT) untuk autentikasi saat push ke remote GitHub
        git push https://github-actions:${{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}}@github.com/nandapu3/Eksperimen_SML_Putri-Nanda-Sari.git
