name: Preprocessing Dataset

on:
  push:
    branches:
      - main
    paths:
      - 'dataset/*'

permissions:
  contents: write

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Detect latest CSV file in dataset folder
      id: get_csv
      run: |
        LATEST_CSV=$(ls -t dataset/*.csv | head -n 1)
        echo "Found latest CSV: $LATEST_CSV"
        echo "csv_path=$LATEST_CSV" >> $GITHUB_OUTPUT

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Putri-Nanda-Sari.py \
          --input "${{ steps.get_csv.outputs.csv_path }}" \
          --output preprocessing/sleep_cycle_preprocessed.csv

    - name: Commit and push processed dataset
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add preprocessing/sleep_cycle_preprocessed.csv
        git add preprocessing/processed_dataset_encoders.json || true
        git commit -m "Automated preprocessing" || echo "Nothing to commit"
    
        # WAJIB: Pakai token kamu, bukan bot
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
    
        # Lakukan push
        git push origin HEAD:main
