name: Preprocessing Dataset

on:
  push:
    branches:
      - main
    paths:
      - 'dataset/*'  

jobs:
  preprocessing:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn  # Menginstal dependensi untuk preprocessing

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Nama-siswa.py  # Menjalankan script preprocessing

    - name: Commit processed dataset to preprocessing folder
      run: |
        git config --global user.name 'GitHub Actions'  # Menyiapkan identitas pengguna
        git config --global user.email 'actions@github.com'  # Menyiapkan email pengguna
        git add preprocessing/processed_dataset.csv  # Menambahkan file yang sudah diproses ke folder preprocessing
        git commit -m "Automated preprocessing"  # Commit hasil preprocessing
        git push  # Mengirim perubahan ke GitHub
